#
# Module manifest for module 'PowerShellBuddy'
#
# Generated by: Attila Krick
#
# Generated on: 18.03.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerShellBuddy.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = 'cb790b27-dcec-458f-888d-47d9e7c6599d'

# Author of this module
Author = 'Attila Krick'

# Company or vendor of this module
CompanyName = 'attilakrick.com'

# Copyright statement for this module
Copyright = '© 2025 Attila Krick. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShellBuddy is a collection of practical cmdlets and helper functions for everyday PowerShell work. It covers logging, formatting, discovery, security checks, prompt helpers, and small utilities for developers, administrators, and trainers.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Public\Get-ModuleUpdate.format.ps1xml', 
               'Public\Get-ParameterInfo.format.ps1xml', 
               'Public\Test-SecurityState.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-Enum', 'Get-Hotkey', 'Get-ModuleUpdate', 'Get-ParameterInfo', 
               'Get-PowerShellNews', 'Get-Quote', 'Get-StrictMode', 'Get-StringHash', 
               'Get-TopTenCmdlet', 'Get-Weather', 'Out-Log', 'Out-Speech', 'Read-Window', 
               'Start-Countdown', 'Test-PSDeveloperReady', 'Test-SecurityState', 
               'Use-NewPrompt'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'en-US\about_PowerShellBuddy_AboutTemplate.help.txt', 
               'en-US\about_PowerShellBuddy.help.txt', 'License.md', 
               'PowerShellBuddy.psd1', 'PowerShellBuddy.psm1', 'Public\Get-Enum.ps1', 
               'Public\Get-Hotkey.ps1', 'Public\Get-ModuleUpdate.format.ps1xml', 
               'Public\Get-ModuleUpdate.ps1', 
               'Public\Get-ParameterInfo.format.ps1xml', 
               'Public\Get-ParameterInfo.ps1', 'Public\Get-PowerShellNews.ps1', 
               'Public\Get-Quote.ps1', 'Public\Get-StrictMode.ps1', 
               'Public\Get-StringHash.ps1', 'Public\Get-TopTenCmdlet.ps1', 
               'Public\Get-Weather.ps1', 'Public\Out-Log.ps1', 
               'Public\Out-Speech.ps1', 'Public\Read-Window.ps1', 
               'Public\Start-Countdown.ps1', 'Public\Test-PSDeveloperReady.ps1', 
               'Public\Test-SecurityState.format.ps1xml', 
               'Public\Test-SecurityState.ps1', 'Public\Use-NewPrompt.ps1', 
               'README.md'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'PowerShellBuddy','AttilaKrick','Developer','Tools','Helpful','Scripting','Debugging','Analysis','Utilities','Productivity','Logging','AdminTools','Training'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/attkri/PowerShellBuddy/blob/main/License.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/attkri/PowerShellBuddy'

        # A URL to an icon representing this module.
        IconUri = 'https://attilakrick.com/media/AKPT-Logo.png'

        # ReleaseNotes of this module
        ReleaseNotes = '
Version 2.0.0:
- Removed **Get-Tipp** from the public module surface.
- Removed the **Get-EuroExchange** example script and its related tests.
- Updated **Get-StringHash** to use PBKDF2-SHA512 for password hashing.
- Refined module packaging, help content, and test coverage.

Version 1.2.1:
- Added new public function **Start-Countdown**.
- Introduced **Build.ps1** in the Private folder for automation tasks.
- Added **License.md** to the module root.
- Improved test coverage and updated existing Pester tests.
- Enhanced module manifest and psm1:
  - Auto-export of public functions (simplifies maintenance).
  - Bugfix: corrected default value of the *Algorithm* parameter in `Get-StringHash` (from SHA256 → SHA512).
- Minor performance improvements and refactoring across several functions.

Version 1.2:
      - New Cmdlet Get-Weather
      - Remove Get-TypeDocumentation
Version 1.1:
      - New Cmdlet Get-StringHash
Version 1.0:
      - Initial release'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

